"""initial schema

Revision ID: 9a93e29dfdca
Revises: 
Create Date: 2026-10-07 21:24:20.093238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a93e29dfdca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=True),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('middle_name', sa.String(length=80), nullable=True),
    sa.Column('surname', sa.String(length=80), nullable=False),
    sa.Column('id_number', sa.String(length=30), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('nationality', sa.String(length=80), nullable=False),
    sa.Column('county', sa.String(length=80), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('postal_address', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('applicants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applicants_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_applicants_id_number'), ['id_number'], unique=False)

    op.create_table('programmes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('target_audience', sa.Text(), nullable=False),
    sa.Column('learning_outcomes', sa.Text(), nullable=False),
    sa.Column('duration_text', sa.String(length=100), nullable=False),
    sa.Column('mode', sa.Enum('physical', 'online', 'blended', name='delivery_mode'), nullable=False),
    sa.Column('cpd_hours', sa.Integer(), nullable=True),
    sa.Column('fee_kes', sa.Integer(), nullable=False),
    sa.Column('brochure_path', sa.String(length=255), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('programmes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_programmes_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_programmes_is_published'), ['is_published'], unique=False)
        batch_op.create_index(batch_op.f('ix_programmes_slug'), ['slug'], unique=True)

    op.create_table('settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'officer', 'viewer', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('intakes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('programme_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('venue', sa.String(length=200), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('application_deadline', sa.Date(), nullable=False),
    sa.Column('reporting_time', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('open', 'closed', 'full', 'cancelled', name='intake_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    with op.batch_alter_table('intakes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_intakes_programme_id'), ['programme_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_intakes_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_intakes_status'), ['status'], unique=False)

    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('reference_no', sa.String(length=40), nullable=True),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('intake_id', sa.Integer(), nullable=False),
    sa.Column('employer', sa.String(length=200), nullable=True),
    sa.Column('job_title', sa.String(length=150), nullable=True),
    sa.Column('highest_qualification', sa.String(length=150), nullable=False),
    sa.Column('institution', sa.String(length=200), nullable=False),
    sa.Column('year_completed', sa.Integer(), nullable=True),
    sa.Column('professional_body', sa.String(length=150), nullable=True),
    sa.Column('membership_no', sa.String(length=60), nullable=True),
    sa.Column('sponsorship', sa.Enum('self', 'employer', name='sponsorship'), nullable=False),
    sa.Column('special_needs', sa.Text(), nullable=True),
    sa.Column('how_heard', sa.String(length=100), nullable=True),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('submitted', 'under_review', 'admitted', 'rejected', 'withdrawn', name='application_status'), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], ),
    sa.ForeignKeyConstraint(['intake_id'], ['intakes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_applicant_id'), ['applicant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_intake_id'), ['intake_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_reference_no'), ['reference_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_applications_status'), ['status'], unique=False)

    op.create_table('admission_letters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('letter_no', sa.String(length=50), nullable=True),
    sa.Column('pdf_path', sa.String(length=255), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('issued_by_id', sa.Integer(), nullable=True),
    sa.Column('emailed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['issued_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id'),
    sa.UniqueConstraint('letter_no')
    )
    op.create_table('application_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.Enum('national_id', 'academic_cert', 'professional_cert', 'cv', 'sponsorship_letter', name='document_type'), nullable=False),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_documents_application_id'), ['application_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_documents_application_id'))

    op.drop_table('application_documents')
    op.drop_table('admission_letters')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_status'))
        batch_op.drop_index(batch_op.f('ix_applications_reference_no'))
        batch_op.drop_index(batch_op.f('ix_applications_intake_id'))
        batch_op.drop_index(batch_op.f('ix_applications_applicant_id'))

    op.drop_table('applications')
    with op.batch_alter_table('intakes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intakes_status'))
        batch_op.drop_index(batch_op.f('ix_intakes_start_date'))
        batch_op.drop_index(batch_op.f('ix_intakes_programme_id'))

    op.drop_table('intakes')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('settings')
    with op.batch_alter_table('programmes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_programmes_slug'))
        batch_op.drop_index(batch_op.f('ix_programmes_is_published'))
        batch_op.drop_index(batch_op.f('ix_programmes_category'))

    op.drop_table('programmes')
    with op.batch_alter_table('applicants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applicants_id_number'))
        batch_op.drop_index(batch_op.f('ix_applicants_email'))

    op.drop_table('applicants')
    # ### end Alembic commands ###
